name: MacOS CI
on:
  push:

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: install dependencies
        run: |
          brew update
          for pkg in openssl autoconf automake libtool nettle p11-kit libtasn1 gettext bison gtk-doc; do
            brew install $pkg || true
          done
          for pkg in nettle wget p11-kit libtasn1; do
            brew upgrade $pkg || true
          done
      - name: update path
        run: |
          echo /usr/local/opt/gettext/bin >>${GITHUB_PATH}
          echo /usr/local/opt/bison/bin >>${GITHUB_PATH}
      - name: bootstrap
        run: ./bootstrap
      - name: configure
        run: |
          CC=clang ./configure --disable-full-test-suite --disable-valgrind-tests --disable-doc --disable-dependency-tracking
      - name: make
        run: |
          make -j$(sysctl -n hw.ncpu) || make -j$(sysctl -n hw.ncpu) V=1
      - uses: actions/upload-artifact@v3.1.3
        with:
          path: .
